name: Playwright Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: playwright
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev

    - name: Run Playwright tests
      run: ${{ secrets.PLAYWRIGHT_RUN_COMMAND }}
      env:
        BASE_URL: ${{ vars.BASE_URL }}
        run: echo ${{ secrets.PLAYWRIGHT_RUN_COMMAND }}

    - name: Generate Allure Report
      run: allure generate allure-results --clean --single-file -o allure-report
      if: ${{ !cancelled() }}

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
